const productos =[
    {
        id: 1,
        titulo: "Sustrato Growers Super Soil (25lt.)" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
    },
    {
        id: 2,
        titulo: "Sustrato Growers Super Soil (50lt.)" ,
        precio: 2500,
        detalle: "",
        categoria: "Fertilizantes",
    },
    {
        id: 1,
        titulo: "Sustrato Growers Super Soil (25lt.)" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
    },
    {
        id: 1,
        titulo: "Sustrato Growers Super Soil (25lt.)" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
    },
    {
        id: 1,
        titulo: "Sustrato Growers Super Soil (25lt.)" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
    },
    {
        id: 1,
        titulo: "Sustrato Growers Super Soil (25lt.)" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
    },
];