

export const productos =[
    {
        id: 1,
        titulo: "Sustrato Growers Super Soil (25lt.)" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen: "https://res.cloudinary.com/dh9c97uci/image/upload/v1673510416/club-cannabico-sustrato-growers-super-soil-20lts_txb77t.jpg"
    },
    {
        id: 2,
        titulo: "Sustrato Growers Super Soil (50lt.)" ,
        precio: 2500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen: "https://res.cloudinary.com/dh9c97uci/image/upload/v1673510416/club-cannabico-sustrato-growers-super-soil-20lts_txb77t.jpg"
    },
    {
        id: 3,
        titulo: "Sustrato Growers Super Soil (50lt.)" ,
        precio: 2500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen: "https://res.cloudinary.com/dh9c97uci/image/upload/v1673510336/Smonkey/products/Captura_de_pantalla_2022-12-15_161139_sn90jh.png"
    },
    {
        id: 4,
        titulo: "Top Crop - Big One 250mL." ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510335/Smonkey/products/Captura_de_pantalla_2022-12-15_160443_iiikrj.png"
    },
    {
        id: 5,
        titulo: "Top Crop - Bloom 250mL." ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen: "https://res.cloudinary.com/dh9c97uci/image/upload/v1673510333/Smonkey/products/TOP_CROP_BLOOM_wxsioe.png"
    },
    {
        id: 7,
        titulo: "Top Crop - Candy 250mL." ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510333/Smonkey/products/TOP_CROP_CANDY_hrunfm.png"
    },
    {
        id: 8,
        titulo: "Top Crop - Deeper 250mL." ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510333/Smonkey/products/TOP_DEEPER_emq3hj.png"
    },
    {
        id: 9,
        titulo: "Clipper - Lighter" ,
        precio: 150,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510337/Smonkey/products/CLIPPER_gjtcd8.png"
    },
    {
        id: 10,
        titulo: "Greenhouse - Feeding (Long) 250g." ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510338/Smonkey/products/GREENHOUSE_FEEDING_LONG_tdn4r9.png"
    },
    {
        id: 11,
        titulo: "Greenhouse - Feeding (Short) 125g." ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510339/Smonkey/products/GREENHOUSE_FEEDING_SHORT_vxtlif.png"
    },
    {
        id: 12,
        titulo: "Greenhouse - Feeding Calcium 500g." ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510338/Smonkey/products/GREENHOUSE_FEEDING_CALCIUM_ihkjwj.png"
    },
    {
        id: 13,
        titulo: "GREENHOUSE FEEDING STARTER KIT MINERAL" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510339/Smonkey/products/GREENHOUSE_FEEDING_STARTER_KIT_gzixcn.png"
    },
    {
        id: 14,
        titulo: "Skogbio - Alga Delta Bioestimulante 100mL." ,
        precio: 1500,
        detalle: "",
        categoria: "Bioestimulante",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510331/Smonkey/products/SKOGBIO_ALGA_DELTA_BIOESTIMULANTE_200ML_4_ntclkh.png"
    },
    {
        id: 15,
        titulo: "Skogbio - Alga Delta Bioestimulante 200mL." ,
        precio: 1500,
        detalle: "",
        categoria: "Bioestimulante",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510331/Smonkey/products/SKOGBIO_ALGA_DELTA_BIOESTIMULANTE_100ML_fm9vbf.png"
    },
    {
        id: 16,
        titulo: "Skogbio - King Clon Gel 25mL." ,
        precio: 1500,
        detalle: "",
        categoria: "Bioestimulante",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510331/Smonkey/products/SKOGBIO_KING_CLON_HORMONA_GEL_25ML_kkddgx.png"
    },
    {
        id: 17,
        titulo: "Mamboreta CONFI - 30cc." ,
        precio: 1500,
        detalle: "",
        categoria: "Pesticida",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510325/Smonkey/products/MAMBORETA_CONFI_ycdovi.png"
    },
    {
        id: 18,
        titulo: "Mamboreta ABA - 30cc." ,
        precio: 1500,
        detalle: "",
        categoria: "Pesticida",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510343/Smonkey/products/MAMBORETA_ABA_30CC_tuzokv.png"
    },
    {
        id: 19,
        titulo: "Mamboreta Fungicida - 30cc." ,
        precio: 1500,
        detalle: "",
        categoria: "Pesticida",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510325/Smonkey/products/MAMBORETA_FUNGICIDA_H_m2yy8a.png"
    },
    {
        id: 20,
        titulo: "Mamboreta TricoTrap - 30cc." ,
        precio: 1500,
        detalle: "",
        categoria: "Pesticida",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510325/Smonkey/products/MAMBORETA_TRICO_TRAP_hfri9g.png"
    },
    {
        id: 21,
        titulo: "Maceta soplada redonda - 3L" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510342/Smonkey/products/MACETA_SOPLADA_trihrt.png"
    },
    {
        id: 22,
        titulo: "Maceta soplada redonda - 10L" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510342/Smonkey/products/MACETA_SOPLADA_trihrt.png"
    },
    {
        id: 23,
        titulo: "Maceta soplada redonda - 12L" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510342/Smonkey/products/MACETA_SOPLADA_trihrt.png"
    },
    {
        id: 24,
        titulo: "Maceta soplada redonda - 15L" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510342/Smonkey/products/MACETA_SOPLADA_trihrt.png"
    },
    {
        id: 25,
        titulo: "Maceta soplada redonda - 20L" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510342/Smonkey/products/MACETA_SOPLADA_trihrt.png"
    },
  
    {
        id: 26,
        titulo: "Raw - Challenge Cone - 33oz." ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510336/Smonkey/products/CHALLENGE_CONE_sw1dnt.png"
    },
    {
        id: 27,
        titulo: "Forestal - Bandeja 4090 (40 celdas, 90cc)" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510338/Smonkey/products/FORESTAL_BANDEJA_4090_yudvwn.png"
    },
    {
        id: 28,
        titulo: "Deses - Pulverizador de Plastico" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510330/Smonkey/products/PULVERIZADOR_DESES_PLAST_yz43ry.png"
    },
    {
        id: 29,
        titulo: "Sauver" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510330/Smonkey/products/SAUVER_ruspce.png"
    },
    {
        id: 30,
        titulo: "Lion Rolling Circus - Pre-Rolled Hemp Gold 24k" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510285/Smonkey/products/IMG_6515_s3fyny.heic"
    },
    {
        id: 31,
        titulo: "Squadfum - Rosing Sauver" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510332/Smonkey/products/SQUAD_FUM_q1oiqb.png"
    },

    {
        id: 32,
        titulo: "Raw - King Size paper (3m.)" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510330/Smonkey/products/RAW_ROLLS_jo7gn6.png"
    },

    {
        id: 33,
        titulo: "Berta - Pulverizador profesional" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510328/Smonkey/products/PULVERIZADOR_BERTA_800CC_bmukok.png"
    },

    {
        id: 34,
        titulo: "Jiffy 7 - Turba prensada (41mm.)" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510340/Smonkey/products/JIFFY_7_MONEDA_TURBA_PRENSADA_uz6q5f.png"
    },

    {
        id: 35,
        titulo: "Pocket - Balanza Pocket" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510333/Smonkey/products/BALANZA_POCKET_gq22fk.png"
    },
    {
        id: 36,
        titulo: "Pirex - Bong Clear" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510321/Smonkey/products/IMG_6541_bt8pfl.heic"
    },

    {
        id: 37,
        titulo: "Garden - Tijera Profesional" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510332/Smonkey/products/TIJERA_MINI_GARDEN_beqy85.png"
    },

    {
        id: 38,
        titulo: "Picador - StarWars: Estrella de la Muerte" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510327/Smonkey/products/PICADOR_ESTRELLA_DE_LA_MUERTE_qtnc3g.png"
    },

    {
        id: 39,
        titulo: "Pipa - Bola 8" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510327/Smonkey/products/PIPA_VIDRIO_BOLA_8_dxzfgb.png"
    },

    {
        id: 40,
        titulo: "Zeus - Tips (Filtros)" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510338/Smonkey/products/FILTROS_ZEUS_TIPS_j5bczf.png"
    },

    {
        id: 41,
        titulo: "SEDAS ZEUS BLACK" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510331/Smonkey/products/SEDAS_ZEUS_BLACK_bfgfjg.jpg"
    },

    {
        id: 42,
        titulo: "Bulldog - Cenicero Deluxe silver" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510335/Smonkey/products/BULLDOG_CENICERO_DELUXE_SILVER_ujfoek.png"
    },

    {
        id: 43,
        titulo: "Bulldog - Cenicero portatil" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510334/Smonkey/products/BULLDOG_CENICERO_PORTATIL_j96far.png"
    },

    {
        id: 44,
        titulo: "Bulldog - Picador transparente (3 pisos) " ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510335/Smonkey/products/BULLDOG_PICADOR_3P_CLEAR_qaiuvj.png"
    },

    {
        id: 45,
        titulo: "Bulldog - Picador negro (3 pisos) " ,
        precio: 1500,
        detalle: "",
        categoria:  "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510335/Smonkey/products/BULLDOG_PICADOR_3P_NEGRO_i9sdty.png"
    },

    {
        id: 46,
        titulo: "Bulldog - Picador (4 partes) Silver" ,
        precio: 1500,
        detalle: "",
        categoria:  "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510336/Smonkey/products/BULLDOG_PICADOR_METAL_4P_SILVER_kxrppy.png"
    },

    {
        id: 47,
        titulo: "Pipe - Glass (vidrio)" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510330/Smonkey/products/PIPA_DE_VIDRIO_GLASS_PIPE2_ojpzky.png"
    },

    {
        id: 48,
        titulo: "Hash Maker - 150micras." ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510340/Smonkey/products/HASH_MAKER_CHICO_150_zavacb.png"
    },

    {
        id: 49,
        titulo: "Hash Maker - 90micras." ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510339/Smonkey/products/HASH_MAKER_CHICO_90_eq7s14.png"
    },

    {
        id: 50,
        titulo: "MINI BONG - Varios" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510325/Smonkey/products/MINI_BONG_CLEAR_VARIOS1_gvkthx.png"
    },

    {
        id: 51,
        titulo: "Lion Rolling Circus - Grinder (3 partes)" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510274/Smonkey/products/IMG_6493_dfwsmx.heic"
    },

    {
        id: 52,
        titulo: "Cerium - Clipper Ash" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510329/Smonkey/products/PIEDRA_CLIPPER_CERIUM_nynhaa.png"
    },

    {
        id: 53,
        titulo: "Pipe - Glass (vidrio)" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510331/Smonkey/products/PIPA_W_DE_VIDRIO_aqurin.png"
    },

    {
        id: 54,
        titulo: "Sauver - (cuadrado)" ,
        precio: 1500,
        detalle: "",
        categoria:  "Parafernalia",
        imagen:""
    },

    {
        id: 55,
        titulo: "Sauver - Traingular (Chico)" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:""
    },

    {
        id: 56,
        titulo: "Rosing recipent " ,
        precio: 1500,
        detalle: "",
        categoria:"Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510336/Smonkey/products/CAZOLETA_SILICONA_REDONDA_QUEMADOR_VIDRIO_SILICONA_x9gj8s.png"
    },

    {
        id: 57,
        titulo: "Blunt Rey - Cenicero Portatil" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510337/Smonkey/products/CENICERO_METAL_qzocfh.png"
    },
    {
        id: 58,
        titulo: "420 - Picador (4 partes, tornasolado)" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510326/Smonkey/products/PICA_TORNASOLADO_4P_nksmvk.png"
    },


    {
        id: 59,
        titulo: "PICADOR ECONOMICO GRANDE" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510328/Smonkey/products/PICADOR_ECONOMICO_GRANDE_qvddsk.png"
    },


    {
        id: 60,
        titulo: "PICADOR ECONOMICO CHICO" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510327/Smonkey/products/PICADOR_ECONOMICO_CHICO_yb08ui.png"
    },

    {
        id: 61,
        titulo: "LION PICADOR DE ALUMINIO 2 PARTES AMSTERDAN" ,
        precio: 1500,
        detalle: "",
        categoria:"Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510341/Smonkey/products/LION_PICADOR_DE_ALUMINIO_2_PARTES_AMSTERDAN_stn0yc.png"
    },

    {
        id: 62,
        titulo: "LION PICADOR DE ALUMINIO 3 PARTES AMSTERDAN" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510341/Smonkey/products/LION_PICADOR_DE_ALUMINIO_3_PARTES_AMSTERDAN_ti9dep.png"
    },

    {
        id: 63,
        titulo: "PICADOR GIZEH METAL 50MM" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510326/Smonkey/products/PICADOR_GIZEH_METAL_50MM_wnydzo.png"
    },

    {
        id: 64,
        titulo: "PIPA CON PICADOR METAL" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510329/Smonkey/products/PIPA_CON_PICADOR_METAL_ofywdk.png"
    },

    {
        id: 65,
        titulo: "MAQUINA PARA ARMAR LION REGULAR" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510333/Smonkey/products/ARMADOR_RAW_ubz5aq.png"
    },

    {
        id: 66,
        titulo: "MAQUINA PARA ARMAR RAW 70MM" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510342/Smonkey/products/LYON_SILVER_KS_110_MM_wzeka3.png"
    },

    {
        id: 67,
        titulo: "PICADOR 420 ARCOIRIS GRANDE 60MM" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510280/Smonkey/products/IMG_6502_qovps7.heic"
    },

    {
        id: 68,
        titulo: "PIPA W DE VIDRIO" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510288/Smonkey/products/IMG_6517_o48me5.heic"
    },

    {
        id: 69,
        titulo: "SEDA CELULOSA 4HEMP" ,
        precio: 1500,
        detalle: "",
        categoria:"Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510337/Smonkey/products/CELULOSA_4HELP_kz4skd.png"
    },

    {
        id: 70,
        titulo: "CIPLOCK" ,
        precio: 1500,
        detalle: "",
        categoria:"Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510337/Smonkey/products/CIPLOCK_rclkke.png"
    },

    {
        id: 71,
        titulo: "LION ROLLING CIRCUS PRE-ROLED HEM GOLD 24K" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510341/Smonkey/products/LION_ORO_xx0wrl.png"
    },

    {
        id: 72,
        titulo: "LION HEMP WRA BLUNT" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510342/Smonkey/products/LION_HEMP_WRA_BLUNT_zcn4bz.png"
    },

    {
        id: 73,
        titulo: "PIPA DE ALUMINIO LLAVERO" ,
        precio: 1500,
        detalle: "",
        categoria:"Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510328/Smonkey/products/PIPA_DE_ALUMINIO_LLAVERO_grvdjz.png"
    },

    {
        id: 74,
        titulo: "SEDAS OCB X-PERT GRIS 1 1/4" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510331/Smonkey/products/SEDAS_OCB_GRIS_i3noao.png"
    },

    {
        id: 75,
        titulo: "FLOWER BLOOM BIOPROYECT 350GR" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510333/Smonkey/products/bioproyect_flower_bloom_350_gr_tdlpn4.png"
    },

    {
        id: 76,
        titulo: "BIOPROYECT FLOWER START 70GR" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510333/Smonkey/products/BIOPROYECT_FLOWER_START_umtvtt.png"
    },

    {
        id: 77,
        titulo: "BIOPROYECT GREEN JUNGLE 70GR" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510334/Smonkey/products/BIOPROYECT_GREEN_JUNGLE_70GR_qgokuv.png"
    },

    {
        id: 78,
        titulo: "BIOPROYECT NUTRIENTES HIDRO PACK 1.2.3.4 150 ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510334/Smonkey/products/BIOPROYECT_NUTRIENTES_HIDRO_PACK_1.2.3.4_150_ML_kqq1v7.png"
    },

    {
        id: 79,
        titulo: "BIOPROYECT SWEET CARBO 50GR" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510334/Smonkey/products/BIOPROYECT_SWEET_CARBON_jyc79n.png"
    },

    {
        id: 80,
        titulo: "POT ARAÑA 200ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Bioestimulante",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510328/Smonkey/products/POT_ARA%C3%91A_iihlme.png"
    },

    {
        id: 81,
        titulo: "POT FLORA 500ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Bioestimulante",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510327/Smonkey/products/POT_FLORA_pklenq.png"
    },

    {
        id: 82,
        titulo: "MACA BREW BIOESTIMULANTE 500CC" ,
        precio: 1500,
        detalle: "",
        categoria:  "Bioestimulante",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510342/Smonkey/products/MACA_BREW_BIOESTIMULANTE_500CC_bstnbt.png"
    },
    {
        id: 83,
        titulo: "POT SUGAR BIO 500ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510330/Smonkey/products/POT_VEGE_BIO_500ML_l1jmcy.png"
    }, 
     {
        id: 84,
        titulo: "POT SUGAR ORG 500ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510329/Smonkey/products/POT_SUGAR_ORG_500ML_n5ppda.png"
    },  
    {
        id: 85,
        titulo: "POT VEGE BIO 500ML" ,
        precio: 1500,
        detalle: "",
        categoria:"Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510329/Smonkey/products/POT_SUGAR_BIO_500_ML_c7nsdt.png"
    },  
    {
        id: 86,
        titulo: "ESTACION HTC-1" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510337/Smonkey/products/ESTACION_HTC_-1_u6flsw.png"
    },  
    {
        id: 87,
        titulo: "FEEDING BOOSTER 125G" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:"https://res.cloudinary.com/dh9c97uci/image/upload/v1673510337/Smonkey/products/FEEDING_BOOSTER_125G_nebwph.png"
    },  
    {
        id: 88,
        titulo: "FILTRO DE AGUA" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:""
    },  
    {
        id: 89,
        titulo: "FILTRO DE AGUA IMAN" ,
        precio: 1500,
        detalle: "",
        categoria:"Herramientas",
        imagen:""
    },  
    {
        id: 90,
        titulo: "GARDEN POLEA XL 68K" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:""
    }, 
     {
        id: 91,
        titulo: "GROTEK BLOSSOM BLASTER PRO 500ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },  
    {
        id: 92,
        titulo: "SOLO TEK BLOOM 250ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    }, 
     {
        id: 93,
        titulo: "SOLO TEK GROW GROTEK 250ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },  
    {
        id: 94,
        titulo: "VITAMAX PRO GROTEK 500ML" ,
        precio: 1500,
        detalle: "",
        categoria:  "Fertilizantes",
        imagen:""
    },  
    {
        id: 95,
        titulo: "GROTEK MONSTER BLOOM 500GR" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },  
    {
        id: 96,
        titulo: "GROTEK MONSTER BLOOM 20GR" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    }, 
     {
        id: 97,
        titulo: "MONSTER BLOOM  GROTEK 130GR" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes", 
        imagen:""
    },  
    {
        id: 98,
        titulo: "INTEGRA MED 4G 55%" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:""
    },  
    {
        id: 99,
        titulo: "INTEGRA MED 67G 55%" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:""
    },  {
        id: 100,
        titulo: "LIXIVIADO DORADO (200 ML)" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },  
    {
        id: 101,
        titulo: "LUPA 22MM 45X LED GALILEO 4522" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:""
    },  
    {
        id: 102,
        titulo: "MAMBORETA FOLI 30CC" ,
        precio: 1500,
        detalle: "",
        categoria: "Pesticida",
        imagen:""
    },  
    {
        id: 103,
        titulo: "CARTAS CANUTO" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:""
    }, 
     {
        id: 104,
        titulo: "FILTRO CANUTO" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:""
    }, 
     {
        id: 105,
        titulo: "SEDAS ZEUS CELULOSA KING SIZE" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:""
    }, 
     {
        id: 106,
        titulo: "CELULOSA ZEUS KING SIZE" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:""
    },  
    {
        id: 107,
        titulo: "RAW SEDAS KS" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:""
    },  
    {
        id: 108,
        titulo: "RAW TIPS FILTROS" ,
        precio: 1500,
        detalle: "",
        categoria:"Parafernalia",
        imagen:""
    }, 
     {
        id: 109,
        titulo: "TOP CROP AUTO 250ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },  
    {
        id: 110,
        titulo: "TOP CROP BARRIER BIOPROTECTOR 100ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Pesticida",
        imagen:""
    },
    {
        id: 111,
        titulo: "TOP CROP BIG ONE BIOESTIMULANTE 250ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Bioestimulante",
        imagen:""
    },
    {
        id: 112,
        titulo: "TOP CROP BUD 100ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Bioestimulante",
        imagen:""
    },
    {
        id: 113,
        titulo: "TOP CROP CALMAG 250ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 114,
        titulo: "REVIENTA COGOLLOS 9.5 500ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 115,
        titulo: "REVIENTA ESQUEJES 30ML" ,
        precio: 1500,
        detalle: "",
        categoria:  "Fertilizantes",
        imagen:""
    },
    {
        id: 116,
        titulo: "REVIENTA PH - 200ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 117,
        titulo: "REVIENTA ESQUEJES 50ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 118,
        titulo: "MANTRA AGUA DE PERRO 250ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 119,
        titulo: "MANTRA ALGAFISHUM NODOSUM ORGANICO 250ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 120,
        titulo: "MANTRA DYNAMITE ORG 250ML" ,
        precio: 1500,
        detalle: "",
        categoria:  "Fertilizantes",
        imagen:""
    },
    {
        id: 121,
        titulo: "MANTRA EL TOQUE FINAL 250ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 122,
        titulo: "MANTRA FLOR DE AUTO 250ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 123,
        titulo: "MANTRA LECHE DE HUESOS 250ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 124,
        titulo: "MANTRA NITRO MONSTRUOSO 250ML" ,
        precio: 1500,
        detalle: "",
        categoria:  "Fertilizantes",
        imagen:""
    },
    {
        id: 125,
        titulo: "MANTRA NITRO MONSTRUOSO ORG 250ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 126,
        titulo: "MANTRA PH- 250 ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 127,
        titulo: "MANTRA SUGAR CANDY 250 ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 128,
        titulo: "NAMASTE AMAZONIA 150GR" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 129,
        titulo: "NAMASTE AMAZONIA 300GR" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 130,
        titulo: "NAMASTE BIOPROTECT 100ML" ,
        precio: 1500,
        detalle: "",
        categoria:  "Fertilizantes",
        imagen:""
    },
    {
        id: 131,
        titulo: "NAMASTE DETOX 500ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 132,
        titulo: "NAMASTE ORO NEGRO 100ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 133,
        titulo: "NAMASTE ORO NEGRO 500ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 134,
        titulo: "NAMASTE PH - 100ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 135,
        titulo: "NAMASTE SHANTI 100ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 136,
        titulo: "NAMASTE SHANTI 500ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Bioestimulante",
        imagen:""
    },
    {
        id: 137,
        titulo: "NAMASTE TRICO + 250GR" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },

    {
        id: 138,
        titulo: "FEEDING GROW 125GR" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 139,
        titulo: "GROTEK MONSTER GROW PRO 130GR" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 140,
        titulo: "LYON HEMP WRAP TERPENES GELATO" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:""
    },
    {
        id: 141,
        titulo: "GREEN HOUSE FEEDING HYBRIDS ALL IN ONE 500GR" ,
        precio: 1500,
        detalle: "",
        categoria:"Fertilizantes",
        imagen:""
    },
    {
        id: 142,
        titulo: "BANDEJAS RAW 28CMX17CM" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:""
    },
    {
        id: 143,
        titulo: "GROTEK SOLO TECK BLOOM 500ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 144,
        titulo: "GROTEK BUD FUEL PRO 500ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes   ",
        imagen:""
    },
    {
        id: 145,
        titulo: "GROTEK HEAVY BUD PRO 500ML" ,
        precio: 1500,
        detalle: "",
        categoria: "Fertilizantes",
        imagen:""
    },
    {
        id: 146,
        titulo: "Tutores" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:""
    },
    {
        id: 147,
        titulo: "TERRA FERTIL TIERRA LOMBRI 5L" ,
        precio: 1500,
        detalle: "",
        categoria: "Herramientas",
        imagen:""
    },
    {
        id: 148,
        titulo: "Buzos" ,
        precio: 1500,
        detalle: "",
        categoria: "Parafernalia",
        imagen:""
    },   

];
